# Generated by Django 4.0.5 on 2022-07-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamiliar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='fecha_nacimiento',
            field=models.DateField(default=(1989, 10, 8)),
            preserve_default=False,
        ),
    ]
