# Generated by Django 4.0.5 on 2022-07-04 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamiliar', '0002_familiar_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiar',
            name='fecha_nacimiento',
        ),
    ]
